In [1]:
#classification

In [2]:
#import dataset MNIST
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784', version=1)
mnist.keys()

dict_keys(['data', 'target', 'frame', 'categories', 'feature_names', 'target_names', 'DESCR', 'details', 'url'])

In [13]:
X, y = mnist["data"], mnist["target"]
print(X.shape, y.shape)

(70000, 784) (70000,)


In [14]:
import matplotlib as mpl
import matplotlib.pyplot as plt

feature_digit = X[0]
feature_0 = feature_digit.reshape(28, 28)

plt.imshow(feature_0, cmap="binary")
plt.axis("off")
plt.show()

KeyError: 0

In [6]:
y[0]

'5'

In [8]:
# train_test_spliit manuel
X_train, X_test, y_train, y_test = X[:60000], X[60000:], y[:60000], y[60000:]

In [9]:
y_train_5 = (y_train == 5)
y_test_5 = (y_test == 5)

In [11]:
from sklearn.linear_model import SGDClassifier

sgdClass = SGDClassifier(random_state = 42)
sgdClass.fit(X_train, y_train_5)

ValueError: The number of classes has to be greater than one; got 1 class

In [16]:
#On evalue un modele de classification soit avec la fonction cross_val_score
# pas vraiment une bonne idee
#Soit avec cross_val_predict qui va effectuer qui est une methode de la matrice de confusion
# alors on va voir si le modele fait passer les instances de class A a la class B
# sachant que parmis les instances passees il y a 3 alors que le target est seulement 5

"""
EX: 
from sklearn.model_selection import cross_val_predict

y_train_pred = cross_val_predict(sgd_clf, X_train, y_train_5, cv=3)
"""

'\nEX: \nfrom sklearn.model_selection import cross_val_predict\n\ny_train_pred = cross_val_predict(sgd_clf, X_train, y_train_5, cv=3)\n'

In [17]:
#Puis on effectue la matrix de confusion, la 1ere ligne est considerer comme instances
# mauvais, la seconde ligne c'est le classement a tort non vrai
"""
EX:
from sklearn.metrics import confusion_matrix
>>> confusion_matrix(y_train_5, y_train_pred)
array([[53057,  1522],
       [ 1325,  4096]])
"""

'\nEX:\nfrom sklearn.metrics import confusion_matrix\n>>> confusion_matrix(y_train_5, y_train_pred)\n'

In [18]:
#Sachant que la gauche signifie instance accusee faux, 
# la droite instance non accuse d'etre faux


#un modele de classification donnerai une telle matrice:
"""
>>> y_train_perfect_predictions = y_train_5  # pretend we reached perfection
>>> confusion_matrix(y_train_5, y_train_perfect_predictions)
 array([[54579,     0],
       [    0,  5421]])
"""

''

In [19]:
#il existe une metrique d'evaluation d'erreur plus precis, c'est le recall:
#le recall c'est le rapport positif correctement detecte par le modele
# la formule est:
#  recall = TP/(TP+FN)
#TP: nombre des vrais positif
#FN: Nombre des faux negatifs


In [ ]:
"""
Avec sklearn:
from sklearn.metrics import precision_score, recall_score
>>> precision_score(y_train_5, y_train_pred) # == 4096 / (4096 + 1522)
0.7290850836596654
>>> recall_score(y_train_5, y_train_pred) # == 4096 / (4096 + 1325)
0.7555801512636044

"""

#precision_score est une fonction qui calcul le score de prediction du modele
#recall_score est le score d'instance correcte 

In [ ]:
#Pour definir son propre seuil pour savoir a partir de combien le recall sera
#inferieur:
"""
>>> y_scores = sgd_clf.decision_function([some_digit])
>>> y_scores
array([2412.53175101])
>>> threshold = 0
>>> y_some_digit_pred = (y_scores > threshold)
array([ True])
"""

In [ ]:
#Pour connaitre a partir de quel seuil le recall sera inferieur il faut utiliser;
# la fonction cross_val_score avec comme method "decision_function"
#Tout ca enregistrer dans une variable
"""
y_scores = cross_val_predict(sgd_clf, X_train, y_train_5, cv=3,
                             method="decision_function")
"""

#puis pour calculer la pression utiliser la fonction "precision_recall-curve"
#Qui est une fonction de sklearn.metrics

"""
from sklearn.metrics import precision_recall_curve

precisions, recalls, thresholds = precision_recall_curve(y_train_5, y_scores)
"""

#Ensuite il faut le visualiser en creant une fonction:
"""
def plot_precision_recall_vs_threshold(precisions, recalls, thresholds):
    plt.plot(thresholds, precisions[:-1], "b--", label="Precision")
    plt.plot(thresholds, recalls[:-1], "g-", label="Recall")
    [...] # highlight the threshold and add the legend, axis label, and grid

plot_precision_recall_vs_threshold(precisions, recalls, thresholds)
plt.show()
"""

#Info: plus le recall est faible plus la precision du modele sera importante

In [1]:
#supposons que nous voulons un modele avec 90% de precision, avec un algorithme
# qui va rechercher le bon seuil, ex: le plus bas de 8000 alors on va faire ceci:
"""
threshold_90_precision = thresholds[np.argmax(precisions >= 0.90)] # ~7816

"""
#Pour effectuer les predictions sur le jeu de donnees actuel au lieu de la methode
#predict() on fait ceci:
"""
y_train_pred_90 = (y_scores >= threshold_90_precision)

"""

#On verifie la precision et le recall:
"""
>>> precision_score(y_train_5, y_train_pred_90)
0.9000380083618396
>>> recall_score(y_train_5, y_train_pred_90)
0.4368197749492714
"""

''